/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirumalee.hirumaleebookshop.view;

import com.hirumalee.hirumaleebookshop.util.DBConnection;
import java.io.FileNotFoundException;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class SalesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesForm.class.getName());

    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProdName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNetTotal = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("                            SALES & BILLING SYSTEM");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18)), "Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Search By ID");

        txtSearchID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtSearchID.addActionListener(this::txtSearchIDActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("Name");

        txtProdName.setEditable(false);
        txtProdName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtProdName.addActionListener(this::txtProdNameActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Unit Price:");

        txtUnitPrice.setEditable(false);
        txtUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUnitPrice.addActionListener(this::txtUnitPriceActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Qty");

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btnAdd.setBackground(new java.awt.Color(0, 102, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        btnAdd.setText("Add to Bill");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchID)
                    .addComponent(txtProdName)
                    .addComponent(txtUnitPrice)
                    .addComponent(txtQty)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProdName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUnitPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Unit Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBill);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Net Total & Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText(" NET TOTAL");

        lblNetTotal.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        lblNetTotal.setText("0.00");

        btnPrint.setBackground(new java.awt.Color(0, 153, 51));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print Bill");
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(lblNetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNetTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(17, 17, 17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(276, 276, 276))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
        try {
    java.sql.Connection con = com.hirumalee.hirumaleebookshop.util.DBConnection.getConnection();
    String sql = "SELECT name, price FROM product WHERE id = ?";
    java.sql.PreparedStatement pstmt = con.prepareStatement(sql);
    pstmt.setString(1, txtSearchID.getText());
    java.sql.ResultSet rs = pstmt.executeQuery();

    if (rs.next()) {
        txtProdName.setText(rs.getString("name"));
        txtUnitPrice.setText(rs.getString("price"));
        txtQty.requestFocus(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Product Not Found!");
        txtSearchID.setText("");
        txtSearchID.requestFocus();
    }
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_txtSearchIDActionPerformed

    private void txtProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdNameActionPerformed

    private void txtUnitPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnitPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnitPriceActionPerformed
     
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
    // 1. NetBeans වල resources වලට යන්නේ නැතුව, කෙලින්ම Jasper Studio එකෙන් ෆයිල් එක ගමු!
        java.io.InputStream reportStream = new java.io.FileInputStream("C:\\Users\\ASUS VIVOBOOK\\JaspersoftWorkspace\\MyReports\\bill_new.jasper");
        // Check if the amount is correctly captured before printing
        String finalAmount = lblNetTotal.getText();
        javax.swing.JOptionPane.showMessageDialog(this, "Amount sending to bill: " + finalAmount);
        
        // 2. Parameters (Net Total එක යවනවා)
        java.util.Map<String, Object> parameters = new java.util.HashMap<>();
        parameters.put("netTotal", lblNetTotal.getText()); 

        // 3. Table එකේ ඩේටා
        net.sf.jasperreports.engine.data.JRTableModelDataSource dataSource = 
        new net.sf.jasperreports.engine.data.JRTableModelDataSource(tblBill.getModel());

        // 4. Report එක පෙන්වනවා
        net.sf.jasperreports.engine.JasperPrint jp = net.sf.jasperreports.engine.JasperFillManager.fillReport(reportStream, parameters, dataSource);
        net.sf.jasperreports.view.JasperViewer.viewReport(jp, false);

    } catch (FileNotFoundException | JRException e) { // JRException වෙනුවට Exception දැම්මා, එතකොට error එන්නේ නෑ
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
        // 1. කොටු හිස්ද කියලා බලනවා (Empty Validation)
        if (txtSearchID.getText().trim().isEmpty() || txtQty.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter both Item ID and Quantity!", "Missing Information", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // මෙතනින් කෝඩ් එක නවතිනවා
        }

        // 2. කොටු වල තියෙන දේවල් ලබා ගන්නවා
        int id = Integer.parseInt(txtSearchID.getText().trim());
        String name = txtProdName.getText().trim();
        double unitPrice = Double.parseDouble(txtUnitPrice.getText().trim());
        int sellingQty = Integer.parseInt(txtQty.getText().trim());
        double total = unitPrice * sellingQty;

        // 3. ඩේටාබේස් එකට කනෙක්ට් වෙලා දැනට ස්ටොක් එක කීයද බලනවා
        java.sql.Connection conn = DBConnection.getConnection(); 
        String checkSql = "SELECT qty FROM product WHERE id = ?";
        java.sql.PreparedStatement checkPst = conn.prepareStatement(checkSql);
        checkPst.setInt(1, id);
        java.sql.ResultSet rs = checkPst.executeQuery();

        if (rs.next()) {
            int currentQty = rs.getInt("qty"); 

            // 4. කස්ටමර් ඉල්ලන ගාණ කඩේ තියෙනවද බලනවා
            if (currentQty >= sellingQty) {
                
                // 4.1 බඩු ටික තියෙනවා නම් විතරක් ටේබල් එකට (බිල් එකට) දානවා
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBill.getModel();
                model.addRow(new Object[]{
                    String.valueOf(id), 
                    name, 
                    String.valueOf(unitPrice), 
                    String.valueOf(sellingQty), 
                    String.valueOf(total)
                });

                // 4.2 ඊට පස්සේ ඩේටාබේස් එකේ ස්ටොක් එක අඩු කරනවා
                String updateSql = "UPDATE product SET qty = qty - ? WHERE id = ?";
                java.sql.PreparedStatement updatePst = conn.prepareStatement(updateSql);
                updatePst.setInt(1, sellingQty);
                updatePst.setInt(2, id);
                updatePst.executeUpdate();

                // 4.3 Net Total එක අප්ඩේට් කරලා, ඊළඟ අයිටම් එක ගහන්න ලේසි වෙන්න කොටු ටික හිස් කරනවා
                calculateNetTotal(); 
                txtSearchID.setText("");
                txtProdName.setText("");
                txtUnitPrice.setText("");
                txtQty.setText("");
                txtSearchID.requestFocus(); // ආයෙත් ID ගහන කොටුවට කර්සරය ගේනවා

            } else if (currentQty == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Out of Stock! This item is currently unavailable.", "Stock Empty", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Insufficient Stock! Only " + currentQty + " items left.", "Low Stock", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid ID! Item not found in database.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        // අකුරු ගහන්න බැරි තැන් වලට අකුරු ගැහුවොත්
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid Numbers for ID, Price, and Quantity!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        // ඩේටාබේස් එකේ මොනවා හරි අවුලක් ගියොත්
        javax.swing.JOptionPane.showMessageDialog(this, "System Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // දැනට ඕපන් වෙලා තියෙන SalesForm එක වහලා දානවා
this.dispose(); 

// ඔයාගේ ප්‍රධාන Dashboard එක ඕපන් කරනවා
new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesForm().setVisible(true));
    }
    private void calculateNetTotal() {
    try {
        double netTotal = 0.0;
            int rows = tblBill.getRowCount();

            for (int i = 0; i < rows; i++) {
                Object value = tblBill.getValueAt(i, 4);
                if (value != null) {
                    // .trim() දාලා spaces අයින් කරලා තමයි Double කරන්නේ
                    netTotal += Double.parseDouble(value.toString().trim());
                }
            }
            lblNetTotal.setText("Rs. " + String.format("%.2f", netTotal));
            
        } catch (NumberFormatException e) {
            System.out.println("Net Total Error: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNetTotal;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearchID;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
