/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hirumalee.hirumaleebookshop.view;

import com.hirumalee.hirumaleebookshop.util.DBConnection;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class UpdateStockForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateStockForm.class.getName());

    /**
     * Creates new form UpdateStockForm
     */
    public UpdateStockForm() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUpdateID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUpdateName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddQty = new javax.swing.JTextField();
        btnUpdateStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("      Item ID");

        txtUpdateID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUpdateIDKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setText("    Item Name");

        txtUpdateName.setEditable(false);
        txtUpdateName.addActionListener(this::txtUpdateNameActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("    Add Quantity");

        btnUpdateStock.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnUpdateStock.setText("Update Stock");
        btnUpdateStock.addActionListener(this::btnUpdateStockActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(txtUpdateID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAddQty, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnUpdateStock)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnUpdateStock, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUpdateNameActionPerformed

    private void txtUpdateIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUpdateIDKeyReleased
        try {
    String searchId = txtUpdateID.getText().trim();
    
    // Clear fields if empty
    if (searchId.isEmpty()) {
        txtUpdateName.setText(""); 
        return;
    }

    // Connect to DB and search
    java.sql.Connection conn = DBConnection.getConnection();
    String sql = "SELECT name FROM product WHERE id = ?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setInt(1, Integer.parseInt(searchId)); 
    java.sql.ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        // Show name and move cursor to Qty field
        txtUpdateName.setText(rs.getString("name"));
        txtAddQty.requestFocus(); 
    } else {
        txtUpdateName.setText("Not Found!");
    }

} catch (Exception e) {
    txtUpdateName.setText("");
}
    }//GEN-LAST:event_txtUpdateIDKeyReleased

    private void btnUpdateStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStockActionPerformed
        try {
    // 1. Validation
    if (txtUpdateID.getText().trim().isEmpty() || txtAddQty.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter ID and Quantity!", "Missing Info", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Get Data
    int itemId = Integer.parseInt(txtUpdateID.getText().trim());
    int newQty = Integer.parseInt(txtAddQty.getText().trim());

    // 3. Update Database (qty = qty + newQty)
    java.sql.Connection conn = DBConnection.getConnection(); 
    String updateSql = "UPDATE product SET qty = qty + ? WHERE id = ?";
    java.sql.PreparedStatement updatePst = conn.prepareStatement(updateSql);
    
    updatePst.setInt(1, newQty);
    updatePst.setInt(2, itemId);
    
    int success = updatePst.executeUpdate();

    // 4. Check Success and Clear
    if (success > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Stock Updated Successfully for: " + txtUpdateName.getText(), "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        txtUpdateID.setText("");
        txtUpdateName.setText("");
        txtAddQty.setText("");
        txtUpdateID.requestFocus(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to update. Check the Item ID.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid Numbers only!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
}
    }//GEN-LAST:event_btnUpdateStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateStockForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddQty;
    private javax.swing.JTextField txtUpdateID;
    private javax.swing.JTextField txtUpdateName;
    // End of variables declaration//GEN-END:variables
}
